### ISSUE TITLE
Version 2.3.2 not available

### ISSUE THREAD

**Issue by adelchiGoalS** [hokolinks/hoko-android#20]
Hi, the project description says to add the 2.3.2 version but is not currently available. Is it a mistake in the readme file?

**Comment by gonmf** [comment]
Hello @adelchiGoalS, thank you for reaching out to us. It is not available as a Maven dependency? Or from https://dl.bintray.com/hoko/maven/com/hokolinks/hoko/2.3.2/ ?

**Comment by adelchiGoalS** [comment]
Hi @gonmf, I mean through gradle.

**Comment by pawlowskim** [comment]
Also, in logcat we can find:
```
04-13 09:18:13.645: E/HOKO(4260): A new version of HOKO is available, please update your gradle.properties to "compile 'com.hokolink:hoko:2.5.0'"
```

**Comment by rikas** [comment]
@pawlowskim I guess that's related to you using the wrong token (iOS instead of Android), right?

**Comment by pawlowskim** [comment]
@rikas Probably yes, because I don't receive it anymore. But still, the error message is misleading.

**Comment by gonmf** [comment]
@adelchiGoalS thank you for your patience, the package should be found now.

**Comment by adelchiGoalS** [comment]
Thank you very much for your assistance @gonmf
